# fly.toml app configuration file generated for fastagency-app-3f6b8b7c-7963-4064-86c1-fcf5c85d6c7b-client on 2024-06-20T04:20:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fastagency-app-3f6b8b7c-7963-4064-86c1-fcf5c85d6c7b-client'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
